title: Aidan Reilly
logo: /assets/img/headshot_circle.png

url: "https://razzi86.github.io"
baseurl: "/Razzi86_first.github.io"

remote_theme: daattali/beautiful-jekyll
plugins:
  - jekyll-remote-theme
